# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        repository: 'caesar269 / catalogs'
        command: 'buildAndPush'
        Dockerfile: 
        buildContext: /src/Services/Catalogs/Dockerfile
        tags: 'latest'